---
- name: "Create openssh_keypair"
  community.crypto.openssh_keypair:
    type: "rsa"
    state: present
    mode: "0600"
    path: "~/.ssh/id_rsa"

- name: "Append ssh authorized_keys"
  ansible.builtin.lineinfile:
    path: "~/.ssh/authorized_keys"
    line: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    create: true
    state: present
    mode: "0600"
