name: tsc_python
channels:
  - conda-forge
dependencies:
  - _openmp_mutex
  - bcrypt
  - bzip2
  - ca-certificates
  - cryptography
  - cx_oracle
  - cyrus-sasl
  - icu
  - keyutils
  - krb5
  - libedit
  - libexpat
  - libffi
  - libgcc-ng
  - libgcc
  - libgomp
  - liblzma
  - libnsl
  - libntlm
  - libpq
  - libsqlite
  - libstdcxx-ng
  - libstdcxx
  - libuuid
  - libxcrypt
  - libzlib
  - ncurses
  - openldap
  - openssl
  - pip
  - psycopg2
  - python_abi
  - python=3.11.15
  - readline
  # - rust
  - setuptools
  - sqlite
  - tk
  - tzdata
  - uv=0.10.11
  - wheel

