name: tsc_python
channels:
  - conda-forge
dependencies:
  - _openmp_mutex
  - backports.zstd
  - bcrypt
  - brotli-python
  - bzip2
  - ca-certificates
  - certifi
  - cffi
  - charset-normalizer
  - cryptography
  - cx_oracle
  - cyrus-sasl
  - decorator
  - h2
  - hpack
  - hyperframe
  - icu
  - idna
  - invoke
  - keyutils
  - krb5
  # - ld_impl_linux-64
  - libedit
  - libexpat
  - libffi
  - libgcc
  - libgcc-ng
  - libgomp
  - liblzma
  - libnsl
  - libntlm
  - libpq
  - libsodium
  - libsqlite
  - libstdcxx
  - libuuid
  - libxcrypt
  - libzlib
  - ncurses
  - openldap
  - openssl
  - packaging
  - paramiko
  - pip
  - psycopg2
  - pycparser
  - pymysql
  - pynacl
  - pyopenssl
  - pysocks
  - python=3.13.12
  - python-gssapi
  - python_abi
  - readline
  - requests
  - setuptools
  - six
  - sqlite
  - tk
  - typing-extensions
  - typing_extensions
  - tzdata
  - urllib3
  - uv
  - wheel
  - zstd