[global]
timeout=30
index-url = http://192.168.19.22/pypi/simple
trusted-host = 
    192.168.19.22
    mirrors.aliyun.com
extra-index-url=
    https://mirrors.cernet.edu.cn/pypi/web/simple
    https://mirrors.cloud.tencent.com/pypi/simple
    https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple
    https://mirrors.huaweicloud.com/repository/pypi/simple
    https://mirrors.aliyun.com/pypi/simple
    https://mirrors.pku.edu.cn/pypi/web/simple
    https://mirrors.njtech.edu.cn/pypi/web/simple
    https://mirror.nju.edu.cn/pypi/web/simple
    https://mirrors.zju.edu.cn/pypi/web/simple
    https://mirrors.bfsu.edu.cn/pypi/web/simple