#!/usr/bin/env bash
export MAMBA_ROOT_PREFIX=/home/tsc/tsc_tools/micromamba
eval "$("${MAMBA_ROOT_PREFIX}"/bin/micromamba shell hook --shell bash)"
micromamba activate tsc_python
export ANSIBLE_CONFIG=/home/tsc/tsc_tools/ansible/ansible.cfg
# alias ansible='ansible -e "ansible_interpreter_python_fallback=/home/tsc/tsc_tools/micromamba/envs/tsc_python/bin/python3:/home/tsc/.pyenv/shims/python3:python3.14:python3.13:python3.12:python3.11:python3.10:python3.9:/usr/bin/python3:python3"'
